export const Alphabet = [
  { letter: 'A', guessed: false },
  { letter: 'B', guessed: false },
  { letter: 'C', guessed: false },
  { letter: 'D', guessed: false },
  { letter: 'E', guessed: false },
  { letter: 'F', guessed: false },
  { letter: 'G', guessed: false },
  { letter: 'H', guessed: false },
  { letter: 'I', guessed: false },
  { letter: 'J', guessed: false },
  { letter: 'K', guessed: false },
  { letter: 'L', guessed: false },
  { letter: 'M', guessed: false },
  { letter: 'N', guessed: false },
  { letter: 'O', guessed: false },
  { letter: 'P', guessed: false },
  { letter: 'Q', guessed: false },
  { letter: 'R', guessed: false },
  { letter: 'S', guessed: false },
  { letter: 'T', guessed: false },
  { letter: 'U', guessed: false },
  { letter: 'V', guessed: false },
  { letter: 'W', guessed: false },
  { letter: 'X', guessed: false },
  { letter: 'Y', guessed: false },
  { letter: 'Z', guessed: false },
]
